[colors.primary]
background = "#050007"
foreground = "#e6c4c0"

[colors.cursor]
text = "#050007"
cursor = "#e6c4c0"

[colors.vi_mode_cursor]
text = "#050007"
cursor = "#e6c4c0"

[colors.search.matches]
foreground = "#050007"
background = "#e6c4c0"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#8b0409"
background = "#e6c4c0"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#050007"
red = "#660000"
green = "#800000"
yellow = "#cc0000"
blue = "#cc0000"
magenta = "#a00000"
cyan = "#fc0303"
white = "#e6c4c0"

[colors.bright]
black = "#8b0409"
red = "#660000"
green = "#800000"
yellow = "#cc0000"
blue = "#cc0000"
magenta = "#a00000"
cyan = "#fc0303"
white = "#e6c4c0"

[colors.dim]
black = "#e6c4c0"
red = "#660000"
green = "#800000"
yellow = "#cc0000"
blue = "#cc0000"
magenta = "#a00000"
cyan = "#fc0303"
white = "#8b0409"
