name = "Neon-Velocity"
author = "mehulrathod-0666"
description = "A high-octane Cyberpunk theme with Neon Purple and Cyan."

accent = "#BF00FF"
cursor = "#00FFFF"
foreground = "#E0E0FF"
background = "#0A0010"
selection_foreground = "#000000"
selection_background = "#00FFFF"

color0 = "#0A0010"
color1 = "#FF0055"
color2 = "#00FF99"
color3 = "#FFFF00"
color4 = "#0099FF"
color5 = "#BF00FF"
color6 = "#00FFFF"
color7 = "#E0E0FF"
color8 = "#2A0030"
color9 = "#FF00AA"
color10 = "#66FF00"
color11 = "#FFEE00"
color12 = "#00CCFF"
color13 = "#E600FF"
color14 = "#00FFFF"
color15 = "#FFFFFF"
