name = "Midnight-Emerald"
author = "mehulrathod-0666"
description = "A deep forest green and black theme for Omarchy."

accent = "#008037"
cursor = "#D0E0D0"
foreground = "#D0E0D0"
background = "#050805"
selection_foreground = "#FFFFFF"
selection_background = "#008037"

color0 = "#050805"
color1 = "#004D1A"
color2 = "#008037"
color3 = "#2E8B57"
color4 = "#004D1A"
color5 = "#008037"
color6 = "#2E8B57"
color7 = "#D0E0D0"
color8 = "#1A251A"
color9 = "#006400"
color10 = "#00A344"
color11 = "#3CB371"
color12 = "#006400"
color13 = "#00A344"
color14 = "#3CB371"
color15 = "#FFFFFF"
