name = "Blood-Moon"
author = "mehulrathod-0666"
description = "A deep, vibrant red and black theme for Omarchy."

accent = "#fc0303"
cursor = "#e6c4c0"
foreground = "#e6c4c0"
background = "#050007"
selection_foreground = "#050007"
selection_background = "#a00000"

color0 = "#1a0002"
color1 = "#660000"
color2 = "#800000"
color3 = "#cc0000"
color4 = "#cc0000"
color5 = "#a00000"
color6 = "#fc0303"
color7 = "#8b0409"
color8 = "#2d0008"
color9 = "#660000"
color10 = "#800000"
color11 = "#cc0000"
color12 = "#cc0000"
color13 = "#a00000"
color14 = "#fc0303"
color15 = "#e6c4c0"
