# Background and foreground colors
background = #050805
foreground = #D0E0D0

# Standard colors
palette = 0=#050805
palette = 1=#004D1A
palette = 2=#008037
palette = 3=#2E8B57
palette = 4=#004D1A
palette = 5=#008037
palette = 6=#2E8B57
palette = 7=#D0E0D0

# Bright colors
palette = 8=#1A251A
palette = 9=#006400
palette = 10=#00A344
palette = 11=#3CB371
palette = 12=#006400
palette = 13=#00A344
palette = 14=#3CB371
palette = 15=#FFFFFF
