# Background and foreground colors
background = #050007
foreground = #e6c4c0

# Standard colors
palette = 0=#050007
palette = 1=#660000
palette = 2=#800000
palette = 3=#cc0000
palette = 4=#cc0000
palette = 5=#a00000
palette = 6=#fc0303
palette = 7=#e6c4c0

# Bright colors
palette = 8=#8b0409
palette = 9=#660000
palette = 10=#800000
palette = 11=#cc0000
palette = 12=#cc0000
palette = 13=#a00000
palette = 14=#fc0303
palette = 15=#e6c4c0
