# This file is not a full hyprland configuration.
# It is intended to be included in your main hyprland.conf.


general {
    col.active_border = rgba(008037ee) rgba(2E8B57ee) 45deg
    col.inactive_border = rgba(05080588)
}

group {
    col.border_active = rgba(008037ee) rgba(2E8B57ee) 45deg
    col.border_inactive = rgba(05080588)
    col.border_locked_active = rgba(2E8B57ee) rgba(008037ee) 45deg
}